# Generated by Django 4.2.30 on 2026-05-26 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco_completo', models.TextField(blank=True)),
                ('historico', models.TextField(blank=True)),
                ('ultima_compra', models.DateTimeField(blank=True, null=True)),
                ('ltv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='RegraFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_inicio', models.CharField(blank=True, max_length=10)),
                ('cep_fim', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frete_gratis_acima_de', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pedido_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prazo_dias', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('total_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'Pix'), ('transferencia', 'Transferência'), ('cartao', 'Cartão')], max_length=20)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando pagamento'), ('pago', 'Pago'), ('separacao', 'Em separação'), ('saiu_entrega', 'Saiu para entrega'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('historico_status', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pix', 'Pix'), ('transferencia', 'Transferência'), ('cartao', 'Cartão')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado')], default='pendente', max_length=20)),
                ('transacao_id', models.CharField(blank=True, max_length=100)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='api.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.produto')),
            ],
        ),
    ]
