# Generated by Django 4.2.30 on 2026-05-25 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TermoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos', to='api.atributo')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao_curta', models.TextField(blank=True)),
                ('descricao_completa', models.TextField(blank=True)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, help_text='Peso em Kg ou formatado pela unidade', max_digits=10, null=True)),
                ('unidade', models.CharField(choices=[('gr', 'Grama'), ('kg', 'Quilograma'), ('mol', 'Molho'), ('unid', 'Unidade'), ('caixa', 'Caixa'), ('bandeja', 'Bandeja'), ('dz', 'Dúzia'), ('sc', 'Saco'), ('pe', 'Peça')], default='unid', max_length=10)),
                ('estoque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produto_ativo', models.BooleanField(default=True)),
                ('produto_em_destaque', models.BooleanField(default=False)),
                ('produto_sazonal', models.BooleanField(default=False)),
                ('produto_organico', models.BooleanField(default=False)),
                ('produto_variavel', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/galeria/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='api.produto')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
