# Generated by Django 4.2.30 on 2026-06-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_banner_cupom_notificacao_movimentacaoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='variacoes',
            field=models.ManyToManyField(blank=True, help_text='Selecione as variações deste produto (ex: Tamanho Médio, Cor Vermelha)', related_name='produtos', to='api.termoatributo'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('cartao', 'Cartão de Crédito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('cartao', 'Cartão de Crédito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('gr', 'Grama'), ('kg', 'Quilograma'), ('mol', 'Molho'), ('unid', 'Unidade'), ('caixa', 'Caixa'), ('bandeja', 'Bandeja'), ('dz', 'Dúzia'), ('sc', 'Saco'), ('pe', 'Pé'), ('lata', 'Lata')], default='unid', max_length=10),
        ),
    ]
