# Generated by Django 4.2.30 on 2026-06-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_produto_variacoes_alter_pagamento_metodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cielo_token',
            field=models.CharField(blank=True, help_text='Token do cartão de crédito na Cielo', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='frequencia_dias',
            field=models.PositiveIntegerField(default=0, help_text='A cada quantos dias o pedido deve se repetir?'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='is_recorrente',
            field=models.BooleanField(default=False),
        ),
    ]
