# Generated by Django 4.2.30 on 2026-06-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cliente_cielo_token_pedido_frequencia_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='produtos_favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritados_por', to='api.produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
