# Generated by Django 4.2.30 on 2026-06-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_categoria_meta_description_categoria_meta_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(default='Horta Viva', max_length=255)),
                ('email_contato', models.EmailField(default='contato@hortaviva.com', max_length=254)),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
                ('endereco_loja', models.TextField(blank=True)),
                ('pedido_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meta_title_global', models.CharField(blank=True, help_text='SEO Title padrão da loja', max_length=255)),
                ('meta_description_global', models.TextField(blank=True, help_text='SEO Description padrão da loja')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.AddField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(default='Notificação', max_length=255),
        ),
    ]
