# Generated by Django 4.2.30 on 2026-06-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_configuracao_notificacao_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.pedido',),
        ),
    ]
