# Generated by Django 4.2.30 on 2026-06-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_relatorioproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='nome_produto',
            field=models.CharField(blank=True, help_text='Nome do produto no momento da compra, incluindo variações (ex: Banana (Verde))', max_length=255),
        ),
    ]
