# Generated by Django 4.2.30 on 2026-06-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pedido_cupom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('nome_cartao', models.CharField(max_length=100)),
                ('validade', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=4)),
                ('is_principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='api.cliente')),
            ],
        ),
    ]
