# Generated by Django 4.2.30 on 2026-06-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='receber_notificacoes',
            field=models.BooleanField(default=False),
        ),
    ]
