# Generated by Django 4.2.30 on 2026-06-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pedido_receber_notificacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_variacao', to='api.produto')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.termoatributo')),
            ],
            options={
                'verbose_name_plural': 'Variações de Preço',
                'unique_together': {('produto', 'termo')},
            },
        ),
    ]
