# Generated by Django 4.2.30 on 2026-06-26 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_populate_missing_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variacaoproduto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='variacoes',
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='atributo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.atributo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='valor',
            field=models.CharField(default='', help_text='Ex: Grande, Médio, Branca, etc.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='variacaoproduto',
            unique_together={('produto', 'atributo', 'valor')},
        ),
        migrations.RemoveField(
            model_name='variacaoproduto',
            name='termo',
        ),
        migrations.DeleteModel(
            name='TermoAtributo',
        ),
    ]
